# -*- coding: utf-8 -*-
"""ASG Commercial Hub: End-to-End Tenant Revenue & Growth Analytics Pipeline .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DpsBwk5Idc7IQUOTqxe-0dahxhiZyI5k
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

np.random.seed(2026)
random.seed(2026)

print("Generating Data")

# 1. SETUP TENANT
tenant_base = [
    {"category": "F&B", "names": ["Kopi Kenangan", "Subway", "Bakmi GM", "Chatime", "Sushi Tei", "Starbucks", "Gacoan", "Shaburi", "Sour Sally", "JCO"]},
    {"category": "Fashion", "names": ["Zara", "Uniqlo", "H&M", "Pull&Bear", "Mango", "Adidas", "Nike", "Mark & Spencer", "Charles & Keith", "Cotton On"]},
    {"category": "Entertainment", "names": ["XXI Cinema", "Timezone", "Fun World", "Celebrity Fitness", "Karaoke Keluarga"]},
    {"category": "Gadget & Electronics", "names": ["iBox", "Samsung Store", "Mi Store", "Erafone", "Asus ROG Store"]}
]

tenant_list = []
tenant_id = 101

for t in tenant_base:
    for name in t["names"]:
        if t["category"] == "Entertainment": area, rent = random.randint(500, 1500), 200000
        elif t["category"] == "Fashion": area, rent = random.randint(150, 500), 300000
        elif t["category"] == "Gadget & Electronics": area, rent = random.randint(80, 200), 400000
        else: area, rent = random.randint(50, 150), 450000

        tenant_list.append({
            "tenant_id": tenant_id, "tenant_name": name, "category": t["category"],
            "leased_area_sqm": area, "monthly_rental_fee": int(area * rent)
        })
        tenant_id += 1

# New Tenant Scenario
tenant_list.append({
    "tenant_id": 151, "tenant_name": "Viral Pastry Shop", "category": "F&B",
    "leased_area_sqm": 80, "monthly_rental_fee": int(80 * 450000)
})

df_tenants = pd.DataFrame(tenant_list)

# 2. SETUP SALES TRANSACTIONS
start_date = datetime(2026, 1, 1)
end_date = datetime(2026, 6, 10)
delta = end_date - start_date

transaction_data = []
transaction_id = 1000001

seasonality = {
    1: {"F&B": 1.0, "Fashion": 1.0, "Entertainment": 1.0, "Gadget & Electronics": 1.0},
    2: {"F&B": 0.95, "Fashion": 0.90, "Entertainment": 0.95, "Gadget & Electronics": 0.95},
    3: {"F&B": 1.50, "Fashion": 1.90, "Entertainment": 0.85, "Gadget & Electronics": 1.15},
    4: {"F&B": 1.10, "Fashion": 1.15, "Entertainment": 1.20, "Gadget & Electronics": 1.05},
    5: {"F&B": 0.80, "Fashion": 0.65, "Entertainment": 0.85, "Gadget & Electronics": 0.75},
    6: {"F&B": 1.10, "Fashion": 1.05, "Entertainment": 1.15, "Gadget & Electronics": 1.00}
}

for i in range(delta.days + 1):
    current_date = start_date + timedelta(days=i)
    m = current_date.month
    day = current_date.day
    is_weekend = current_date.weekday() in [5, 6]
    is_payday = day >= 25 and day <= 28
    is_midnight_sale = (m == 5 and day == 30)

    for tenant in tenant_list:
        tid = tenant["tenant_id"]
        cat = tenant["category"]

        # Scenario 1a
        if tid == 104 and m >= 3: continue

        # Scenario 1b
        if tid == 151 and m < 5: continue

        # Scenario 2
        if tid == 125 and m >= 5: continue

        if cat == "F&B": base_tx, price_range = random.randint(30, 60), (35000, 120000)
        elif cat == "Fashion": base_tx, price_range = random.randint(8, 25), (250000, 800000)
        elif cat == "Entertainment": base_tx, price_range = random.randint(12, 35), (50000, 150000)
        else: base_tx, price_range = random.randint(2, 8), (1000000, 5000000)

        # Scenario 3
        if tid in [119, 120]:
            base_tx = int(base_tx * (1 - (m * 0.06))) # Turun 6% tiap bulan


        if is_weekend: base_tx = int(base_tx * random.uniform(1.4, 1.7))
        if is_payday: base_tx = int(base_tx * 1.25)
        if is_midnight_sale: base_tx = int(base_tx * 2.5) # Lonjakan Ekstrem Event

        # Generate Transaction
        for _ in range(max(1, base_tx)):
            amount = random.randint(price_range[0], price_range[1])
            final_amount = int(amount * seasonality[m][cat] * random.uniform(0.9, 1.1))

            if is_midnight_sale:
                final_amount = int(final_amount * 1.3) # Keranjang belanja lebih penuh saat diskon

            transaction_data.append({
                "transaction_id": transaction_id, "tenant_id": tid,
                "date": current_date.strftime("%Y-%m-%d"), "amount": final_amount
            })
            transaction_id += 1

df_sales = pd.DataFrame(transaction_data)

# 3. SETUP MONTHLY BILLS
bill_data = []
bill_id = 5001
months = ["2026-01", "2026-02", "2026-03", "2026-04", "2026-05"]

for month in months:
    m_int = int(month.split("-")[1])
    for tenant in tenant_list:
        tid = tenant["tenant_id"]
        if tid == 104 and m_int >= 3: continue
        if tid == 151 and m_int < 5: continue
        if tid == 125 and m_int >= 5: continue

        service_charge = tenant["leased_area_sqm"] * 45000

        if tid == 125 and m_int == 4: status = "Unpaid"
        elif tid in [119, 120] and m_int >= 4: status = random.choice(["Late", "Unpaid"])
        else: status = random.choice(["Paid"] * 92 + ["Late"] * 6 + ["Unpaid"] * 2)

        bill_data.append({
            "bill_id": bill_id, "tenant_id": tid, "billing_month": month,
            "service_charge_fee": service_charge, "payment_status": status
        })
        bill_id += 1

df_bills = pd.DataFrame(bill_data)

# EXPORT
df_tenants.to_csv("dim_tenants.csv", index=False)
df_sales.to_csv("fact_sales_transactions.csv", index=False)
df_bills.to_csv("fact_monthly_bills.csv", index=False)

print("\n Finished")
print(f"Total Row: {df_sales.shape[0]} logs.")